[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspaces --include-workspace-root"]

[phases.build]
cmds = [
  "cd apps/api && npx prisma generate",
  "cd apps/api && npm run build"
]

[start]
cmd = "cd apps/api && npm start"